name: Bamba Availability Checker

on:
  schedule:
    # Fires at minute 0 every hour UTC → your script adds a small jitter
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check-bamba:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps & Playwright
        run: |
          pip install --upgrade pip
          pip install playwright cryptography
          playwright install chromium

      - name: Run Bamba Checker
        env:
          FERNET_KEY:  ${{ secrets.FERNET_KEY }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT:   ${{ secrets.SMTP_PORT }}
          SMTP_USER:   ${{ secrets.SMTP_USER }}
          SMTP_PASS:   ${{ secrets.SMTP_PASS }}
          FROM_EMAIL:  ${{ secrets.FROM_EMAIL }}
        run: python bamba_checker.py

      - name: Upload Screenshots & History
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bamba-output
          path: |
            coles_screenshots/
            history.json
