name: Bamba Availability Checker

on:
  schedule:
    # every hour on the hour UTC; script itself gates 07–23 AWST and +/-10 min
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check_bamba:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies & Playwright
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      - name: Run Checker
        env:
          FERNET_KEY:  ${{ secrets.FERNET_KEY }}
          SMTP_USER:   ${{ secrets.SMTP_USER }}
          SMTP_PASS:   ${{ secrets.SMTP_PASS }}
          SMTP_SERVER: smtp.gmail.com
          SMTP_PORT:   587
          FROM_EMAIL:  ${{ secrets.SMTP_USER }}
        run: python bamba_checker.py

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bamba-output
          path: |
            coles_screenshots/
            bamba_results/
            history.json
