name: Bamba Daily Summary Email

on:
  schedule:
    # 07:00 UTC = 15:00 AWST
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  summary:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code (includes history.json)
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with: python-version: '3.10'

      - name: Install crypto lib
        run: pip install cryptography

      - name: Send daily summary
        env:
          FERNET_KEY:  ${{ secrets.FERNET_KEY }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT:   ${{ secrets.SMTP_PORT }}
          SMTP_USER:   ${{ secrets.SMTP_USER }}
          SMTP_PASS:   ${{ secrets.SMTP_PASS }}
          FROM_EMAIL:  ${{ secrets.FROM_EMAIL }}
        run: python daily_summary.py
