name: 🥜 Bamba Daily Summary

on:
  # every day at 07:00 UTC (15:00 AWST)
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  send_summary:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Send Daily Summary Email
        env:
          # your secrets must be added in Settings → Secrets → Actions
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          FERNET_KEY:         ${{ secrets.FERNET_KEY }}
        run: python daily_summary.py
