# .github/workflows/daily-summary.yml
name: Bamba Daily Summary

on:
  schedule:
    - cron: '0 7 * * *'  # Run at 7 AM UTC (3 PM AWST)
  workflow_dispatch:  # Allow manual runs too

jobs:
  send-summary:
    runs-on: ubuntu-latest
    env:
      TZ: Australia/Perth  # Set timezone to AWST
      FERNET_KEY: ${{ secrets.FERNET_KEY }}
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Daily Summary
      run: python daily_summary.py
