name: Bamba Daily Summary

on:
  schedule:
    # 07:00 UTC = 15:00 AWST
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Daily Summary
        env:
          FERNET_KEY:  ${{ secrets.FERNET_KEY }}
          SMTP_USER:   ${{ secrets.SMTP_USER }}
          SMTP_PASS:   ${{ secrets.SMTP_PASS }}
          SMTP_SERVER: smtp.gmail.com
          SMTP_PORT:   587
          FROM_EMAIL:  ${{ secrets.SMTP_USER }}
        run: python daily_summary.py
