# .github/workflows/daily-summary.yml
name: Bamba Daily Summary Email

on:
  schedule:
    # every day at 07:00 UTC (15:00 AWST)
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  send_summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install sendgrid

      - name: Send Daily Summary
        env:
          FERNET_KEY: ${{ secrets.FERNET_KEY }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: python daily_summary.py
